# Generated by Django 5.1.6 on 2025-02-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyprofile_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='city',
            new_name='company_city',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='country',
            new_name='company_country',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='state_or_region',
        ),
    ]
